#!/usr/bin/env python3
"""Render, stage, and verify the Rover Bean Raspberry Pi appliance."""

from __future__ import annotations

import argparse
import base64
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import platform
import pwd
import grp
import re
import shutil
import stat
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
MANIFEST_PATH = HERE / "appliance-v1.json"
GENERATED_ROOT = HERE / "generated"
AUDIT_BACKUP_SOURCE = HERE / "audit_backup.py"
APPLIANCE_SOURCE = HERE / "appliance.py"
BEGIN_MARKER = "# BEGIN ROVER BEAN APPLIANCE V1"
END_MARKER = "# END ROVER BEAN APPLIANCE V1"


class ApplianceError(ValueError):
    """The requested appliance state is invalid or unsafe to apply."""


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="milliseconds")


def load_manifest() -> dict:
    return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))


def root_path(root: Path, absolute: str) -> Path:
    if not absolute.startswith("/"):
        raise ApplianceError(f"appliance path must be absolute: {absolute}")
    return root / absolute.removeprefix("/")


def rendered_files() -> dict[str, str]:
    return {
        "/etc/ssh/sshd_config.d/10-rover-bean.conf": """# Generated by software/appliance/appliance.py.
PermitRootLogin no
PasswordAuthentication no
KbdInteractiveAuthentication no
PubkeyAuthentication yes
AuthenticationMethods publickey
AllowUsers agent
X11Forwarding no
ExposeAuthInfo yes
""",
        "/etc/sudoers.d/rover-bean-agent": """# D030: the resident agent has full authority over the Pi.
agent ALL=(ALL:ALL) NOPASSWD: ALL
""",
        "/etc/tlog/tlog-rec-session.conf": json.dumps(
            {
                "shell": "/bin/bash",
                "notice": "\nRover Bean session recording is active. Pi-local records are not tamper-proof.\n\n",
                "latency": 1,
                "payload": 2048,
                "log": {"input": True, "output": True, "window": True},
                "writer": "file",
                "file": {"path": "/var/log/agent-sessions/tlog.jsonl"},
            },
            indent=2,
        ) + "\n",
        "/etc/udev/rules.d/70-rover-pico-uart.rules": (
            '# RP1 UART0 on GPIO14/15; do not alias the Pi 5 debug UART10.\n'
            'SUBSYSTEM=="tty", KERNEL=="ttyAMA*", '
            'PROGRAM=="/usr/bin/readlink -f /sys%p/device/of_node", '
            'RESULT=="*/rp1/serial@30000", '
            'SYMLINK+="rover-pico", GROUP="robot", MODE="0660"\n'
        ),
        "/etc/systemd/system/rover-cloudflared.service": """[Unit]
Description=Rover Bean outbound-only Cloudflare Tunnel
After=network-online.target
Wants=network-online.target
ConditionPathExists=/etc/cloudflared/rover-bean.token

[Service]
Type=simple
User=cloudflared
Group=cloudflared
ExecStart=/usr/bin/cloudflared tunnel --no-autoupdate run --token-file /etc/cloudflared/rover-bean.token
Restart=on-failure
RestartSec=5
NoNewPrivileges=true
PrivateTmp=true
PrivateDevices=true
ProtectSystem=strict
ProtectHome=true
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
RestrictSUIDSGID=true
LockPersonality=true
CapabilityBoundingSet=
AmbientCapabilities=
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6 AF_NETLINK
ReadOnlyPaths=/etc/cloudflared/rover-bean.token

[Install]
WantedBy=multi-user.target
""",
        "/etc/systemd/system/rover-audit-backup.service": """[Unit]
Description=Rover Bean session backup with explicit mount gaps
After=local-fs.target

[Service]
Type=simple
User=agent
Group=robot
ExecStart=/opt/rover-bean/appliance/audit_backup.py
Restart=on-failure
RestartSec=2
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=read-only
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
RestrictSUIDSGID=true
LockPersonality=true
ReadWritePaths=/var/log/agent-sessions /var/log/rover-audit /var/lib/rover-bean-audit /mnt/robot-audit

[Install]
WantedBy=multi-user.target
""",
        "/usr/local/libexec/rover-bean-login": """#!/usr/bin/env bash
set -u
recorder=/usr/bin/tlog-rec-session
config=/etc/tlog/tlog-rec-session.conf
session_dir=/var/log/agent-sessions
event_file=/var/log/rover-audit/events.jsonl
logger=/usr/bin/logger
fallback_shell=/bin/bash
audit_session=
boot_id=

if [[ ${ROVER_BEAN_LOGIN_TEST:-0} == 1 ]]; then
  recorder=${ROVER_BEAN_TLOG:?test recorder required}
  config=${ROVER_BEAN_TLOG_CONFIG:?test config required}
  session_dir=${ROVER_BEAN_SESSION_DIR:?test session dir required}
  event_file=${ROVER_BEAN_EVENT_FILE:?test event file required}
  logger=${ROVER_BEAN_LOGGER:?test logger required}
  fallback_shell=${ROVER_BEAN_FALLBACK_SHELL:?test shell required}
  audit_session=${ROVER_BEAN_AUDIT_SESSION:?test audit session required}
  boot_id=${ROVER_BEAN_BOOT_ID:?test boot ID required}
elif [[ -r /proc/self/sessionid ]]; then
  audit_session=$(/usr/bin/tr -d '[:space:]' </proc/self/sessionid)
  boot_id=$(/usr/bin/tr -d '[:space:]-' </proc/sys/kernel/random/boot_id)
fi

capture_failure() {
  local status=$1
  "${logger}" -p authpriv.alert -t rover-agent-capture -- "capture_failure status=${status}; external collector must alarm"
  /usr/bin/printf '{"kind":"capture_failure","status":%d}\n' "${status}" >> "${event_file}" 2>/dev/null || true
}

if [[ -x "${recorder}" && -r "${config}" && -d "${session_dir}" && -w "${session_dir}" &&
      ${audit_session} =~ ^[0-9]+$ && ${boot_id} =~ ^[0-9A-Za-z]+$ ]]; then
  session_pattern='"session"[[:space:]]*:[[:space:]]*'${audit_session}'([,}])'
  boot_pattern='"rec"[[:space:]]*:[[:space:]]*"'${boot_id}'-'
  already_recorded=0
  if [[ -f "${session_dir}/tlog.jsonl" ]] &&
      /usr/bin/grep -E "${boot_pattern}" "${session_dir}/tlog.jsonl" |
        /usr/bin/grep -Eq "${session_pattern}"; then
    already_recorded=1
  fi
  before_size=0
  if [[ -f "${session_dir}/tlog.jsonl" ]]; then
    before_size=$(/usr/bin/wc -c < "${session_dir}/tlog.jsonl")
  fi
  "${recorder}" "$@"
  recorder_status=$?
  after_size=0
  if [[ -f "${session_dir}/tlog.jsonl" ]]; then
    after_size=$(/usr/bin/wc -c < "${session_dir}/tlog.jsonl")
  fi
  if [[ ${already_recorded} -eq 1 ]]; then
    exit "${recorder_status}"
  fi
  if [[ ${after_size} -gt ${before_size} ]] &&
      /usr/bin/tail -c "+$((before_size + 1))" "${session_dir}/tlog.jsonl" |
        /usr/bin/grep -E "${boot_pattern}" |
        /usr/bin/grep -Eq "${session_pattern}"; then
    exit "${recorder_status}"
  fi
  capture_failure "${recorder_status}"
else
  capture_failure 127
fi

if [[ ${1:-} == -c ]]; then
  # The recorder may already have executed a non-idempotent remote command.
  # Raise the gap alarm and preserve its status; never replay the command.
  exit "${recorder_status:-125}"
fi
exec "${fallback_shell}" "$@"
""",
    }


def validate_manifest(manifest: dict) -> None:
    if manifest.get("appliance_id") != "RB-PI-APPLIANCE-V1":
        raise ApplianceError("unexpected appliance_id")
    expected_paths = set(rendered_files()) | {
        "/opt/rover-bean/appliance/appliance.py",
        "/opt/rover-bean/appliance/appliance-v1.json",
        "/opt/rover-bean/appliance/audit_backup.py",
    }
    file_rows = manifest.get("files", [])
    actual_paths = {row.get("path") for row in file_rows}
    if actual_paths != expected_paths or len(file_rows) != len(actual_paths):
        raise ApplianceError("closed-world generated file set changed")
    sudo_name = Path("/etc/sudoers.d/rover-bean-agent").name
    if "." in sudo_name or sudo_name.endswith("~"):
        raise ApplianceError("sudoers filename would be ignored")
    if not Path("/etc/ssh/sshd_config.d/10-rover-bean.conf").name.endswith(".conf"):
        raise ApplianceError("sshd drop-in must end in .conf")
    if manifest["secrets"]["access_service_token_location"].split(";")[0] != "remote client only":
        raise ApplianceError("Access service token must remain off the Pi")


def _mode_for(manifest: dict, path: str) -> int:
    row = next(row for row in manifest["files"] if row["path"] == path)
    return int(row["mode"], 8)


def generate(check: bool) -> None:
    manifest = load_manifest()
    validate_manifest(manifest)
    outputs = {
        GENERATED_ROOT / path.removeprefix("/"): content
        for path, content in rendered_files().items()
    }
    stale = [
        str(path.relative_to(ROOT))
        for path, content in outputs.items()
        if not path.exists() or path.read_text(encoding="utf-8") != content
    ]
    if check:
        expected_existing = set(outputs)
        actual_existing = {path for path in GENERATED_ROOT.rglob("*") if path.is_file()}
        extras = sorted(str(path.relative_to(ROOT)) for path in actual_existing - expected_existing)
        stale.extend(f"unexpected {path}" for path in extras)
        if stale:
            raise SystemExit(f"STALE_APPLIANCE_ARTIFACTS: {', '.join(stale)}")
        print("RB_PI_APPLIANCE_RENDER_PASS")
        return
    for path, content in outputs.items():
        atomic_write(
            path,
            content,
            _mode_for(manifest, "/" + str(path.relative_to(GENERATED_ROOT))),
        )
        print(f"wrote {path.relative_to(ROOT)}")


def validate_public_key(payload: str) -> str:
    if "PRIVATE KEY" in payload or "\r" in payload:
        raise ApplianceError("private keys and CR characters are forbidden")
    lines = payload.splitlines()
    if len(lines) != 1 or not lines[0].strip():
        raise ApplianceError("exactly one SSH public key line is required")
    parts = lines[0].split(maxsplit=2)
    if len(parts) not in (2, 3) or parts[0] != "ssh-ed25519":
        raise ApplianceError("only option-free Ed25519 public keys are accepted")
    try:
        decoded = base64.b64decode(parts[1], validate=True)
    except (ValueError, base64.binascii.Error) as exc:
        raise ApplianceError("invalid SSH public-key base64") from exc
    offset = 0

    def read_ssh_string() -> bytes:
        nonlocal offset
        if offset + 4 > len(decoded):
            raise ApplianceError("truncated Ed25519 public-key blob")
        length = int.from_bytes(decoded[offset:offset + 4], "big")
        offset += 4
        value = decoded[offset:offset + length]
        if len(value) != length:
            raise ApplianceError("truncated Ed25519 public-key blob")
        offset += length
        return value

    if read_ssh_string() != b"ssh-ed25519" or len(read_ssh_string()) != 32:
        raise ApplianceError("invalid Ed25519 public-key wire format")
    if offset != len(decoded):
        raise ApplianceError("trailing data in Ed25519 public-key blob")
    return " ".join(parts) + "\n"


def public_key_fingerprint(public_key: str) -> str:
    blob = base64.b64decode(public_key.split()[1], validate=True)
    digest = base64.b64encode(hashlib.sha256(blob).digest()).decode().rstrip("=")
    return f"SHA256:{digest}"


def validate_tunnel_token(payload: str) -> str:
    if "\r" in payload:
        raise ApplianceError("tunnel token contains CR")
    token = payload.strip()
    if len(token) < 50 or any(character.isspace() for character in token):
        raise ApplianceError("tunnel token must be one opaque line of at least 50 characters")
    return token + "\n"


def validate_console_password_hash(payload: str) -> str:
    if "\r" in payload:
        raise ApplianceError("console password hash contains CR")
    password_hash = payload.strip()
    if not re.fullmatch(
        r"\$y\$[./0-9A-Za-z]+\$[./0-9A-Za-z]{1,86}\$[./0-9A-Za-z]{43}",
        password_hash,
    ):
        raise ApplianceError("console password hash must be one yescrypt $y$ line")
    return password_hash


def atomic_write(path: Path, content: str | bytes, mode: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    data = content.encode() if isinstance(content, str) else content
    with tempfile.NamedTemporaryFile(dir=path.parent, delete=False) as stream:
        stream.write(data)
        stream.flush()
        os.fsync(stream.fileno())
        temp = Path(stream.name)
    os.chmod(temp, mode)
    os.replace(temp, path)


def update_managed_block(existing: str, lines: list[str]) -> str:
    block = BEGIN_MARKER + "\n" + "\n".join(lines) + "\n" + END_MARKER
    pattern = re.compile(
        rf"(?ms)^{re.escape(BEGIN_MARKER)}$.*?^{re.escape(END_MARKER)}$"
    )
    if pattern.search(existing):
        updated = pattern.sub(block, existing)
    else:
        updated = existing.rstrip("\n") + "\n\n" + block + "\n"
    return updated.rstrip("\n") + "\n"


def stage_root(root: Path, public_key_path: Path, token_path: Path,
               skip_security_files: bool = False) -> None:
    manifest = load_manifest()
    validate_manifest(manifest)
    for directory in manifest["directories"]:
        path = root_path(root, directory["path"])
        path.mkdir(parents=True, exist_ok=True)
        os.chmod(path, int(directory["mode"], 8))
    for absolute, content in rendered_files().items():
        if skip_security_files and absolute in {
            "/etc/ssh/sshd_config.d/10-rover-bean.conf",
            "/etc/sudoers.d/rover-bean-agent",
        }:
            continue
        atomic_write(root_path(root, absolute), content, _mode_for(manifest, absolute))
    atomic_write(
        root_path(root, "/opt/rover-bean/appliance/appliance.py"),
        APPLIANCE_SOURCE.read_bytes(),
        _mode_for(manifest, "/opt/rover-bean/appliance/appliance.py"),
    )
    atomic_write(
        root_path(root, "/opt/rover-bean/appliance/appliance-v1.json"),
        MANIFEST_PATH.read_bytes(),
        _mode_for(manifest, "/opt/rover-bean/appliance/appliance-v1.json"),
    )
    atomic_write(
        root_path(root, "/opt/rover-bean/appliance/audit_backup.py"),
        AUDIT_BACKUP_SOURCE.read_bytes(),
        _mode_for(manifest, "/opt/rover-bean/appliance/audit_backup.py"),
    )
    boot_path = root_path(root, manifest["uart"]["boot_config_path"])
    if not boot_path.exists():
        raise ApplianceError(f"missing Raspberry Pi boot config: {boot_path}")
    boot = update_managed_block(boot_path.read_text(encoding="utf-8"),
                                manifest["uart"]["managed_lines"])
    atomic_write(boot_path, boot, stat.S_IMODE(boot_path.stat().st_mode))
    public_key = validate_public_key(public_key_path.read_text(encoding="utf-8"))
    atomic_write(root_path(root, manifest["secrets"]["authorized_keys"]), public_key, 0o600)
    tunnel_token = validate_tunnel_token(token_path.read_text(encoding="utf-8"))
    atomic_write(root_path(root, manifest["secrets"]["tunnel_token"]), tunnel_token, 0o400)
    print("RB_PI_APPLIANCE_STAGE_PASS secrets=redacted ownership=live-install-only")


def parse_version(text: str) -> tuple[int, int, int]:
    match = re.search(r"(?<!\d)(\d{4})\.(\d{1,2})\.(\d+)(?!\d)", text)
    if not match:
        raise ApplianceError(f"cannot parse cloudflared version from {text!r}")
    return tuple(int(value) for value in match.groups())


def static_findings(root: Path) -> list[str]:
    manifest = load_manifest()
    findings: list[str] = []
    try:
        validate_manifest(manifest)
    except ApplianceError as exc:
        return [str(exc)]
    for absolute, content in rendered_files().items():
        path = root_path(root, absolute)
        if not path.exists():
            findings.append(f"missing {absolute}")
            continue
        if path.read_text(encoding="utf-8") != content:
            findings.append(f"content drift {absolute}")
        expected_mode = _mode_for(manifest, absolute)
        if stat.S_IMODE(path.stat().st_mode) != expected_mode:
            findings.append(f"mode drift {absolute}")
    source_files = {
        "/opt/rover-bean/appliance/appliance.py": APPLIANCE_SOURCE,
        "/opt/rover-bean/appliance/appliance-v1.json": MANIFEST_PATH,
        "/opt/rover-bean/appliance/audit_backup.py": AUDIT_BACKUP_SOURCE,
    }
    for absolute, source in source_files.items():
        target = root_path(root, absolute)
        if not target.exists() or target.read_bytes() != source.read_bytes():
            findings.append(f"source missing or drifted: {absolute}")
        elif stat.S_IMODE(target.stat().st_mode) != _mode_for(manifest, absolute):
            findings.append(f"mode drift {absolute}")
    boot_path = root_path(root, manifest["uart"]["boot_config_path"])
    if not boot_path.exists():
        findings.append("boot config missing")
    else:
        boot = boot_path.read_text(encoding="utf-8")
        if boot.count(BEGIN_MARKER) != 1 or boot.count(END_MARKER) != 1:
            findings.append("UART managed block missing or duplicated")
        for line in manifest["uart"]["managed_lines"]:
            if line not in boot:
                findings.append(f"UART setting missing: {line}")
    secret_modes = {
        manifest["secrets"]["authorized_keys"]: 0o600,
        manifest["secrets"]["tunnel_token"]: 0o400,
    }
    for absolute, mode in secret_modes.items():
        path = root_path(root, absolute)
        if not path.exists() or stat.S_IMODE(path.stat().st_mode) != mode:
            findings.append(f"secret missing or wrong mode: {absolute}")
    return findings


def _command(command: list[str]) -> tuple[int, str]:
    result = subprocess.run(command, text=True, capture_output=True, check=False)
    return result.returncode, (result.stdout + result.stderr).strip()


def live_findings(root: Path) -> list[str]:
    if root.resolve() != Path("/"):
        return ["live verification requires --root /"]
    manifest = load_manifest()
    findings: list[str] = []
    try:
        model = Path("/proc/device-tree/model").read_text(encoding="utf-8").rstrip("\0")
    except OSError:
        model = ""
    if manifest["target"]["model_contains"] not in model:
        findings.append("live model is not Raspberry Pi 5")
    if platform.machine() != manifest["target"]["architecture"]:
        findings.append("live architecture is not aarch64")
    try:
        os_release = Path("/etc/os-release").read_text(encoding="utf-8")
    except OSError:
        os_release = ""
    if "VERSION_CODENAME=bookworm" not in os_release:
        findings.append("live OS is not Debian/Raspberry Pi OS Bookworm")
    try:
        kernel_command_line = Path("/proc/cmdline").read_text(encoding="utf-8")
    except OSError:
        kernel_command_line = ""
    debug_console_declared = any(value in kernel_command_line for value in (
        "console=ttyAMA10", "console=serial0"
    ))
    if not debug_console_declared:
        findings.append("Pi 5 debug UART10 is absent from the kernel console command line")
    serial0 = Path("/dev/serial0")
    if not serial0.exists() or serial0.resolve().name != "ttyAMA10":
        findings.append("/dev/serial0 does not resolve to the Pi 5 debug UART10")
    stable = Path(manifest["uart"]["stable_device"])
    if not stable.exists() or stable.resolve().name != "ttyAMA0":
        findings.append("/dev/rover-pico does not resolve to RP1 UART0")
    of_node = Path("/sys/class/tty/ttyAMA0/device/of_node")
    try:
        resolved_of_node = of_node.resolve(strict=True)
        full_name = "/" + str(resolved_of_node.relative_to(
            "/sys/firmware/devicetree/base"
        ))
    except OSError:
        full_name = ""
    except ValueError:
        full_name = ""
    if not full_name.endswith(manifest["uart"]["rp1_of_node_suffix"]):
        findings.append("ttyAMA0 OF-node is not RP1 UART0 serial@30000")
    code, effective = _command(["sshd", "-T"])
    required_sshd = {
        "permitrootlogin no", "passwordauthentication no",
        "kbdinteractiveauthentication no", "pubkeyauthentication yes",
        "authenticationmethods publickey", "x11forwarding no", "exposeauthinfo yes",
    }
    if code or not required_sshd.issubset(set(effective.lower().splitlines())):
        findings.append("sshd effective key-only configuration is not proven")
    code, cloud_version = _command(["cloudflared", "--version"])
    try:
        version_ok = parse_version(cloud_version) >= parse_version(
            manifest["cloudflared"]["minimum_version"]
        )
    except ApplianceError:
        version_ok = False
    if code or not version_ok:
        findings.append("cloudflared 2025.4.0+ is not proven")
    for service in (
        "ssh.service", "auditd.service", "rover-cloudflared.service",
        "rover-audit-backup.service",
    ):
        code, unused = _command(["systemctl", "is-active", "--quiet", service])
        if code:
            findings.append(f"required service is not active: {service}")
    debug_getty_active = any(
        _command(["systemctl", "is-active", "--quiet", service])[0] == 0
        for service in ("serial-getty@ttyAMA10.service", "serial-getty@serial0.service")
    )
    if not debug_getty_active:
        findings.append("Pi 5 debug UART10 serial getty is not active")
    code, unused = _command([
        "systemctl", "is-active", "--quiet", "serial-getty@ttyAMA0.service"
    ])
    if code == 0:
        findings.append("RP1 GPIO UART0 incorrectly has a serial getty")
    for absolute, owner, group in (
        (manifest["secrets"]["authorized_keys"], "agent", "agent"),
        (manifest["secrets"]["tunnel_token"], "cloudflared", "cloudflared"),
    ):
        path = Path(absolute)
        try:
            actual_owner = pwd.getpwuid(path.stat().st_uid).pw_name
            actual_group = grp.getgrgid(path.stat().st_gid).gr_name
        except (OSError, KeyError):
            actual_owner = actual_group = ""
        if (actual_owner, actual_group) != (owner, group):
            findings.append(f"wrong live owner/group: {absolute}")
    if not os.path.ismount(manifest["recording"]["backup_mount"]):
        findings.append("off-host backup mount is absent; this is availability only")
    for marker in ("ssh.json", "access.json", "console.json", "collector.json"):
        if not Path("/var/lib/rover-bean-attest", marker).exists():
            findings.append(f"missing live attestation {marker}")
    return findings


def write_attestation(root: Path, name: str, record: dict[str, object]) -> None:
    path = root_path(root, f"/var/lib/rover-bean-attest/{name}.json")
    record = {"ts": utc_now(), **record}
    atomic_write(path, json.dumps(record, sort_keys=True) + "\n", 0o600)


def attest_ssh(root: Path, environ: dict[str, str] | None = None,
               username: str | None = None) -> dict[str, str]:
    environ = os.environ if environ is None else environ
    username = username or os.environ.get("USER", "")
    if username != "agent" or not environ.get("SSH_CONNECTION"):
        raise ApplianceError("attest-ssh must run as agent inside the fresh SSH session")
    auth_info_path = environ.get("SSH_USER_AUTH")
    if not auth_info_path:
        raise ApplianceError("SSH_USER_AUTH is absent; ExposeAuthInfo is not effective")
    auth_info = Path(auth_info_path).read_text(encoding="utf-8")
    match = re.search(r"(ssh-ed25519|sk-ssh-ed25519@openssh\.com)\s+([A-Za-z0-9+/=]+)",
                      auth_info)
    if not match:
        raise ApplianceError("authenticated public key is absent from SSH_USER_AUTH")
    public_key = f"{match.group(1)} {match.group(2)}"
    record = {
        "kind": "fresh_ssh_pubkey_session",
        "connection": environ["SSH_CONNECTION"],
        "fingerprint": public_key_fingerprint(public_key),
    }
    write_attestation(root, "ssh", record)
    return record


def attest_console(root: Path, tty_path: str | None = None,
                   username: str | None = None) -> dict[str, str]:
    username = username or os.environ.get("USER", "")
    if tty_path is None:
        try:
            tty_path = os.ttyname(sys.stdin.fileno())
        except OSError as exc:
            raise ApplianceError("attest-console requires an interactive serial TTY") from exc
    resolved = str(Path(tty_path).resolve())
    if username != "agent" or not resolved.endswith("ttyAMA10"):
        raise ApplianceError("attest-console must run as agent on Pi 5 debug UART10")
    record = {"kind": "debug_uart_emit_and_input", "tty": resolved}
    write_attestation(root, "console", record)
    return record


def attest_access(root: Path, hostname: str, edge_log_id: str,
                  environ: dict[str, str] | None = None,
                  username: str | None = None) -> dict[str, str]:
    environ = os.environ if environ is None else environ
    username = username or os.environ.get("USER", "")
    if username != "agent" or not environ.get("SSH_CONNECTION"):
        raise ApplianceError("attest-access must run as agent in the fresh Access SSH session")
    if not re.fullmatch(r"[A-Za-z0-9.-]+", hostname) or "." not in hostname:
        raise ApplianceError("a valid Access application hostname is required")
    if not re.fullmatch(r"[A-Za-z0-9._:-]{8,256}", edge_log_id):
        raise ApplianceError("a Cloudflare Access edge log identifier is required")
    record = {
        "kind": "cloudflare_access_proxycommand_session",
        "hostname": hostname,
        "edge_log_id": edge_log_id,
        "connection": environ["SSH_CONNECTION"],
    }
    write_attestation(root, "access", record)
    return record


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="validate tracked generated files")
    sub = parser.add_subparsers(dest="command")
    stage = sub.add_parser("stage-root")
    stage.add_argument("--root", type=Path, required=True)
    stage.add_argument("--ssh-public-key-file", type=Path, required=True)
    stage.add_argument("--tunnel-token-file", type=Path, required=True)
    stage.add_argument("--skip-security-files", action="store_true")
    version = sub.add_parser("check-cloudflared-version")
    version.add_argument("version_text")
    password_hash = sub.add_parser("check-console-password-hash")
    password_hash.add_argument("path", type=Path)
    verify = sub.add_parser("verify")
    verify.add_argument("--root", type=Path, default=Path("/"))
    verify.add_argument("--live", action="store_true")
    verify.add_argument("--json", action="store_true")
    attest_ssh_parser = sub.add_parser("attest-ssh")
    attest_ssh_parser.add_argument("--root", type=Path, default=Path("/"))
    attest_console_parser = sub.add_parser("attest-console")
    attest_console_parser.add_argument("--root", type=Path, default=Path("/"))
    attest_access_parser = sub.add_parser("attest-access")
    attest_access_parser.add_argument("--root", type=Path, default=Path("/"))
    attest_access_parser.add_argument("--hostname", required=True)
    attest_access_parser.add_argument("--edge-log-id", required=True)
    args = parser.parse_args()
    if args.check:
        generate(True)
        return
    if args.command is None:
        generate(False)
    elif args.command == "stage-root":
        stage_root(args.root, args.ssh_public_key_file, args.tunnel_token_file,
                   args.skip_security_files)
    elif args.command == "check-cloudflared-version":
        required = parse_version(load_manifest()["cloudflared"]["minimum_version"])
        actual = parse_version(args.version_text)
        if actual < required:
            raise SystemExit(
                f"cloudflared {actual} is below required {required}"
            )
        print("RB_CLOUDFLARED_VERSION_PASS")
    elif args.command == "check-console-password-hash":
        validate_console_password_hash(args.path.read_text(encoding="utf-8"))
        print("RB_CONSOLE_PASSWORD_HASH_PASS")
    elif args.command == "verify":
        findings = static_findings(args.root)
        if args.live:
            findings.extend(live_findings(args.root))
        result = {
            "appliance_id": load_manifest()["appliance_id"],
            "scope": "live" if args.live else "static",
            "pass": not findings,
            "findings": findings,
        }
        print(json.dumps(result, indent=2, sort_keys=True) if args.json else (
            "RB_PI_APPLIANCE_VERIFY_PASS" if not findings
            else "RB_PI_APPLIANCE_VERIFY_BLOCKED\n- " + "\n- ".join(findings)
        ))
        raise SystemExit(0 if not findings else 1)
    elif args.command == "attest-ssh":
        print(json.dumps(attest_ssh(args.root), sort_keys=True))
    elif args.command == "attest-console":
        print(json.dumps(attest_console(args.root), sort_keys=True))
    elif args.command == "attest-access":
        print(json.dumps(attest_access(
            args.root, args.hostname, args.edge_log_id
        ), sort_keys=True))


if __name__ == "__main__":
    main()
