#!/usr/bin/env bash
set -euo pipefail

usage() {
  echo "Usage: sudo software/install.sh --ssh-public-key-file PATH --tunnel-token-file PATH --console-password-hash-file PATH --access-ready" >&2
}

if [[ ${EUID} -ne 0 ]]; then
  usage
  echo "Run this installer as root." >&2
  exit 1
fi

ssh_public_key_file=
tunnel_token_file=
console_password_hash_file=
access_ready=0
cloudflare_key_temp=
sshd_backup=
cleanup_temp_files() {
  [[ -z ${cloudflare_key_temp} ]] || rm -f "${cloudflare_key_temp}"
  [[ -z ${sshd_backup} ]] || rm -f "${sshd_backup}"
}
trap cleanup_temp_files EXIT
while [[ $# -gt 0 ]]; do
  case "$1" in
    --ssh-public-key-file)
      [[ $# -ge 2 ]] || { usage; exit 2; }
      ssh_public_key_file=$2
      shift 2
      ;;
    --tunnel-token-file)
      [[ $# -ge 2 ]] || { usage; exit 2; }
      tunnel_token_file=$2
      shift 2
      ;;
    --console-password-hash-file)
      [[ $# -ge 2 ]] || { usage; exit 2; }
      console_password_hash_file=$2
      shift 2
      ;;
    --access-ready)
      access_ready=1
      shift
      ;;
    *)
      usage
      echo "Unknown argument: $1" >&2
      exit 2
      ;;
  esac
done

if [[ -z ${ssh_public_key_file} || -z ${tunnel_token_file} || \
      -z ${console_password_hash_file} || ${access_ready} -ne 1 ]]; then
  usage
  echo "A public key, tunnel token, and pre-created Cloudflare Access policy are mandatory." >&2
  exit 2
fi
if [[ ! -r ${ssh_public_key_file} || ! -r ${tunnel_token_file} || \
      ! -r ${console_password_hash_file} ]]; then
  echo "The public-key, tunnel-token, and console-hash input files must be readable." >&2
  exit 2
fi

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
install_root=/opt/rover-bean
appliance_tool=${repo_root}/software/appliance/appliance.py
generated_root=${repo_root}/software/appliance/generated

model=$(tr -d '\0' </proc/device-tree/model 2>/dev/null || true)
if [[ ${model} != *"Raspberry Pi 5"* || $(uname -m) != aarch64 ]]; then
  echo "Refusing to provision: this contract requires an aarch64 Raspberry Pi 5." >&2
  exit 3
fi
if ! grep -q '^VERSION_CODENAME=bookworm$' /etc/os-release; then
  echo "Refusing to provision: Raspberry Pi OS/Debian Bookworm is required." >&2
  exit 3
fi

python3 "${appliance_tool}" --check
python3 "${appliance_tool}" check-console-password-hash "${console_password_hash_file}"

robotd_was_enabled=0
robotd_was_active=0
systemctl is-enabled --quiet robotd.service 2>/dev/null && robotd_was_enabled=1
systemctl is-active --quiet robotd.service 2>/dev/null && robotd_was_active=1

apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates curl gnupg
install -d -m 0755 /usr/share/keyrings
cloudflare_key_temp=$(mktemp /usr/share/keyrings/cloudflare-main.gpg.XXXXXX)
curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg -o "${cloudflare_key_temp}"
chmod 0644 "${cloudflare_key_temp}"
mv "${cloudflare_key_temp}" /usr/share/keyrings/cloudflare-main.gpg
cloudflare_key_temp=
printf '%s\n' 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared any main' \
  >/etc/apt/sources.list.d/cloudflared.list
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install -y \
  auditd ca-certificates cloudflared curl openssh-server python3 python3-venv rsync sudo tlog

cloudflared_version=$(cloudflared --version)
python3 "${appliance_tool}" check-cloudflared-version "${cloudflared_version}"

getent group robot >/dev/null || groupadd --system robot
id agent >/dev/null 2>&1 || useradd --create-home --shell /bin/bash agent
id cloudflared >/dev/null 2>&1 || useradd --system --home-dir /nonexistent \
  --no-create-home --shell /usr/sbin/nologin cloudflared
usermod -a -G robot,dialout,sudo agent
console_password_hash=$(tr -d '\n' <"${console_password_hash_file}")
printf 'agent:%s\n' "${console_password_hash}" | chpasswd -e
unset console_password_hash

python3 -m venv "${install_root}/venv"
"${install_root}/venv/bin/pip" install --no-deps "${repo_root}/software/robotd"
install -D -m 0644 "${repo_root}/software/systemd/robotd.service" \
  /etc/systemd/system/robotd.service
install -d -o agent -g robot -m 0750 /var/log/robotd

# Stage non-security files first. sudoers and sshd are installed only after their
# native validators accept the exact generated bytes.
python3 "${appliance_tool}" stage-root --root / \
  --ssh-public-key-file "${ssh_public_key_file}" \
  --tunnel-token-file "${tunnel_token_file}" \
  --skip-security-files

sudoers_source=${generated_root}/etc/sudoers.d/rover-bean-agent
visudo -cf "${sudoers_source}"
install -o root -g root -m 0440 "${sudoers_source}" /etc/sudoers.d/rover-bean-agent

sshd_source=${generated_root}/etc/ssh/sshd_config.d/10-rover-bean.conf
sshd_target=/etc/ssh/sshd_config.d/10-rover-bean.conf
sshd_backup=$(mktemp)
sshd_had_previous=0
if [[ -f ${sshd_target} ]]; then
  cp -p "${sshd_target}" "${sshd_backup}"
  sshd_had_previous=1
fi
rollback_sshd() {
  if [[ ${sshd_had_previous} -eq 1 ]]; then
    install -o root -g root -m 0644 "${sshd_backup}" "${sshd_target}"
  else
    rm -f "${sshd_target}"
  fi
}
install -o root -g root -m 0644 "${sshd_source}" "${sshd_target}"
if ! sshd -t; then
  rollback_sshd
  rm -f "${sshd_backup}"
  sshd_backup=
  echo "sshd rejected the key-only configuration; the previous file was restored." >&2
  exit 4
fi
sshd_effective=$(sshd -T)
for required in \
  'permitrootlogin no' \
  'passwordauthentication no' \
  'kbdinteractiveauthentication no' \
  'pubkeyauthentication yes' \
  'authenticationmethods publickey' \
  'x11forwarding no' \
  'exposeauthinfo yes'; do
  if ! grep -qx "${required}" <<<"${sshd_effective}"; then
    rollback_sshd
    rm -f "${sshd_backup}"
    sshd_backup=
    echo "sshd effective configuration is missing: ${required}" >&2
    exit 4
  fi
done
rm -f "${sshd_backup}"
sshd_backup=

chown -R agent:agent /home/agent/.ssh
chmod 0700 /home/agent/.ssh
chmod 0600 /home/agent/.ssh/authorized_keys
chown -R cloudflared:cloudflared /etc/cloudflared
chmod 0750 /etc/cloudflared
chmod 0400 /etc/cloudflared/rover-bean.token
for path in /var/lib/rover-bean-audit /var/lib/rover-bean-attest \
  /var/log/agent-sessions /var/log/rover-audit /mnt/robot-audit; do
  chown agent:robot "${path}"
  chmod 0750 "${path}"
done
touch /var/log/agent-sessions/tlog.jsonl /var/log/rover-audit/events.jsonl
chown agent:robot /var/log/agent-sessions/tlog.jsonl /var/log/rover-audit/events.jsonl
chmod 0640 /var/log/agent-sessions/tlog.jsonl /var/log/rover-audit/events.jsonl
usermod --shell /usr/local/libexec/rover-bean-login agent

udevadm control --reload-rules
udevadm trigger --subsystem-match=tty
systemctl daemon-reload
systemctl enable --now ssh.service auditd.service rover-cloudflared.service rover-audit-backup.service
systemctl reload ssh.service

# Never start or stop robotd here. First install remains disabled/stopped; a
# rerun preserves both pre-existing state bits.
if [[ ${robotd_was_enabled} -eq 1 ]]; then
  systemctl enable robotd.service
else
  systemctl disable robotd.service
fi
if [[ ${robotd_was_active} -eq 1 ]]; then
  echo "Preserved the already-running robotd process; restart it explicitly after reboot/UART attestation."
fi

python3 "${appliance_tool}" verify --root /

cat <<'EOF'
RB_PI_APPLIANCE_INSTALL_PASS

DO NOT CLOSE THIS SESSION YET.
1. From a second terminal, prove a fresh key-only login as agent and run:
     python3 /opt/rover-bean/appliance/appliance.py attest-ssh
   Then bind the matching Cloudflare Access log event with attest-access; see
   docs/pi-appliance-provisioning.md in the source checkout.
2. Reboot. On the physical Pi 5 debug UART10 console, log in as agent and run:
     python3 /opt/rover-bean/appliance/appliance.py attest-console
3. Confirm /dev/rover-pico resolves to RP1 UART0 on GPIO14/15, then run:
     sudo python3 /opt/rover-bean/appliance/appliance.py verify --live

The Pi never stores Cloudflare Access service tokens. Configure them only on
remote ProxyCommand clients. The RW /mnt/robot-audit copy is backup, not a trust
anchor; the separately administered append-only collector still requires proof.
robotd remains in its pre-install enabled/running state. Keep the motor branch
physically isolated until the commissioning gates say otherwise.
EOF
